data "discord_permission" "deny_all" {
  add_reactions               = "deny"
  administrator               = "deny"
  attach_files                = "deny"
  ban_members                 = "deny"
  change_nickname             = "deny"
  connect                     = "deny"
  create_events               = "deny"
  create_expressions          = "deny"
  create_instant_invite       = "deny"
  create_private_threads      = "deny"
  create_public_threads       = "deny"
  deafen_members              = "deny"
  embed_links                 = "deny"
  kick_members                = "deny"
  manage_channels             = "deny"
  manage_emojis               = "deny"
  manage_events               = "deny"
  manage_guild                = "deny"
  manage_messages             = "deny"
  manage_nicknames            = "deny"
  manage_roles                = "deny"
  manage_threads              = "deny"
  manage_webhooks             = "deny"
  mention_everyone            = "deny"
  moderate_members            = "deny"
  move_members                = "deny"
  mute_members                = "deny"
  priority_speaker            = "deny"
  read_message_history        = "deny"
  request_to_speak            = "deny"
  send_messages               = "deny"
  send_thread_messages        = "deny"
  send_tts_messages           = "deny"
  send_voice_messages         = "deny"
  speak                       = "deny"
  start_embedded_activities   = "deny"
  stream                      = "deny"
  use_application_commands    = "deny"
  use_external_emojis         = "deny"
  use_external_sounds         = "deny"
  use_external_stickers       = "deny"
  use_soundboard              = "deny"
  use_vad                     = "deny"
  view_audit_log              = "deny"
  view_channel                = "deny"
  view_guild_insights         = "deny"
  view_monetization_analytics = "deny"
}

data "discord_permission" "deny_channel" {
  view_channel = "deny"
}

data "discord_permission" "allow_channel" {
  view_channel = "allow"
}