name: Terraform Format

on:
  pull_request:

jobs:
  terraform:
    name: "Terraform Format"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Format
        id: fmt
        run: terraform -chdir=modules/ fmt -check -recursive
      # Run a terraform validate
      - name: Terraform Validate
        id: validate
        # Run even if formatting fails
        if: success() || failure()
        run: terraform -chdir=modules/ validate -no-color
